### ISSUE TITLE
divvy-vertical-control interfering with scrolling

### ISSUE THREAD

**Issue by tmilker** [ractivejs/learn.ractivejs.org#19]
The divvy-vertical-control between the tutorial text and the template and code areas for horizontal resizing is interfering with the scrolling of the tutorial text.  It overlaps the scrollbar by more than 50% which makes it more likely to start a resize when you go to scroll the tutorial down by dragging.  This happens in Chrome 41, Firefox 35 and IE 11 and can get real frustrating.

A possible solution that works in Chrome is:

```css
.divvy-leaf.divvy-left {
  z-index: 11;
}
```

This CSS my be too general though, I don't know how divvy works.

**Comment by Madgvox** [comment]
Wow, good catch.
