### ISSUE TITLE
Simple examples

### ISSUE THREAD

**Issue by thigrand** [ractivejs/learn.ractivejs.org#25]
Add simple examples to your DOCs. Like MDN does. 
For example http://docs.ractivejs.org/latest/ractive-get don't explain anything. 
Sometimes description on MDN also are useless, but simple examples do the thing.

**Comment by fskreuz** [comment]
This is best filed under https://github.com/ractivejs/docs.ractivejs.org. And yes, we do need to have better examples. :+1:

**Comment by thigrand** [comment]
As you wish;P

**Comment by thigrand** [comment]
As you wish;P
